name: scaibu_mutex_lock
description: >
  A Dart package for mutex locking, ensuring safe and efficient 
  synchronization. Supports atomic ops, deadlock prevention, and 
  lightweight resource locking.

version: 1.0.5
homepage: https://github.com/Chief-Strategist-J/scaibu_mutex_lock
repository: https://github.com/Chief-Strategist-J/scaibu_mutex_lock
issue_tracker: https://github.com/Chief-Strategist-J/scaibu_mutex_lock/issues
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"



dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter


dev_dependencies:
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:

platforms:
  android:
  ios:
  macos:
  windows:
  linux: