name: scaibu_mutex_lock
description: >
  A Dart package for mutex locking, ensuring safe and efficient 
  synchronization. Supports atomic ops, deadlock prevention, and 
  lightweight resource locking.

version: 1.0.9
homepage: https://github.com/Chief-Strategist-J/scaibu_mutex_lock
repository: https://github.com/Chief-Strategist-J/scaibu_mutex_lock
issue_tracker: https://github.com/Chief-Strategist-J/scaibu_mutex_lock/issues
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"



dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  mockito: ^5.4.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1


dev_dependencies:
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  build_runner: ^2.4.15

flutter:

platforms:
  android:
  ios:
  macos:
  windows:
  linux: